//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyDeTai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HuongDan
    {
        public int MaDeTai { get; set; }
        public int MaGV { get; set; }
        public Nullable<int> Diem { get; set; }
        public string NhanXet { get; set; }
    
        public virtual DeTai DeTai { get; set; }
        public virtual GiangVien GiangVien { get; set; }
    }
}
